services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./database/:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - product-distribution-api-network

    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        image: product-distribution-api
        container_name: product-distribution-api-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        environment:
            DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}"
        depends_on:
            - db
        networks:
            - product-distribution-api-network

    nginx:
        image: nginx:1.17-alpine
        container_name: product-distribution-api-nginx
        restart: unless-stopped
        ports:
            - "${API_PORT}:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - product-distribution-api-network

networks:
    product-distribution-api-network:
        driver: bridge
